nombre_estudiante = input("Por favor ingrese su nombre ")
edad_estudiante = int(input("Por favor ingrese la edad del estudiante "))
print("El nombre del estudiante es "+ nombre_estudiante)
print("La edad del estudiante es "+ str(edad_estudiante))
anio_actual = int(input("Por favor ingrese el año en curso "))
print("El año de nacimiento es "+ str(anio_actual - edad_estudiante))
nota_fundamentos = float(input("Ingrese nota "))
print("La nota es "+ str(nota_fundamentos))
